### ISSUE TITLE
Provide a method to join new virt devices to an existing fleet

### ISSUE THREAD

**Issue by klutchell** [balena-labs-research/balena-virt#10]
**Is your feature request related to a problem? Please describe.**

When new virt devices come online it would be convenient to automatically join them to an existing fleet.

**Describe the solution you'd like**

Maybe an optional env var `JOIN_FLEET` (and `API_TOKEN`) could be used to automatically join devices to a balenaCloud fleet? I guess that would require the balenaCLI or at least reproducing the steps taken by the join command over SSH.

**Describe alternatives you've considered**

I also considered pre-configuring (and maybe preloading) the image, or allowing a custom balenaOS image path, but it seems that a special image release is being used.

**Comment by maggie44** [comment]
Mini brainstorm here out loud for reference. I don't think the preloading would be possible now as the OS is downloaded on first run rather than packaged in the image. This allowed for always using the latest OS, and since Cloudflare proxy is enabled there appears to be far fewer failures or slow build times with this method. 

That leaves either including a config file downloaded from the Cloud at the root, or passing an API key which then configures the image. Would it need manually extracting from the config.json though? That feels clunky. 

Maybe including the whole config.json as an env var. 

Or an API key and fleet name and then it executes a `join` command, but seems like it is more susceptible to typos than the config.json approach. 

Alternatively something a bit more fancy, should OS images that are not on the Cloud, provide a URL that when visited from a logged in Cloud account are added? Wider reaching than just a Virt implementation though. Or more Virt centric, a web UI could start on first run and wait for a config file to be pasted in...

**Comment by klutchell** [comment]
I think providing an API key and a Fleet slug would be enough to run balena os configure.

**Comment by maggie44** [comment]
Similar to:

> Or an API key and fleet name and then it executes a join command, but seems like it is more susceptible to typos than the config.json approach.

But with a configure instead of join after starting, which would be more efficient. Seems clean and simple, fairly problem free. Shame about having such wide reaching API keys.
